// SPDX-License-Identifier: GPL-2.0-or-later

// Code generated by scripts/sync-drivedb-go.sh from native/drivedb/drivedb.h; DO NOT EDIT.

package exec

// DrivedbUpstreamCommit is the upstream smartmontools commit SHA from which
// the embedded drivedb.h was taken.
const DrivedbUpstreamCommit = "76e88dac82ba"

// DrivedbUpstreamDate is the commit date of DrivedbUpstreamCommit in RFC 3339 format.
const DrivedbUpstreamDate = "2026-09-09T11:17:15Z"
