#!/usr/bin/env bash
# scripts/sync-drivedb-go.sh — sync the Go module's embedded drivedb.h copy
# from the authoritative native/drivedb/drivedb.h.
#
# go:embed cannot reach outside its module directory, and `go get` on
# bindings/go only ever receives that subtree — there is no native/ in the
# module zip a consumer downloads. So bindings/go/backends/exec/drivedb.h
# must be a physical copy, refreshed by this script whenever
# native/drivedb/drivedb.h changes upstream. native/drivedb/drivedb.h is the
# single source of truth; never hand-edit the Go copy or drivedb_version.go.
#
# Usage: scripts/sync-drivedb-go.sh
#
# CI (ci-bindings-go.yml) runs this and fails the build if it produces a
# diff, which is what makes "single source of truth" enforced rather than
# aspirational.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SRC="${REPO_ROOT}/native/drivedb/drivedb.h"
DST_DIR="${REPO_ROOT}/bindings/go/backends/exec"
DST="${DST_DIR}/drivedb.h"
VERSION_GO="${DST_DIR}/drivedb_version.go"

if [ ! -f "${SRC}" ]; then
  echo "sync-drivedb-go.sh: ${SRC} not found" >&2
  exit 1
fi

# The VERSION entry looks like:
#   { "VERSION: 7.5/6178 2026-06-29 15:47:49 +0000 6c5eac3c22f7",
# i.e. "VERSION: <release>/<svn-rev> <date> <time> +0000 <git-sha>".
VERSION_LINE="$(grep -m1 'VERSION: ' "${SRC}")"
if [[ ! "${VERSION_LINE}" =~ VERSION:\ [0-9.]+/[0-9]+\ ([0-9]{4}-[0-9]{2}-[0-9]{2})\ ([0-9]{2}:[0-9]{2}:[0-9]{2})\ \+0000\ ([0-9a-f]+) ]]; then
  echo "sync-drivedb-go.sh: could not parse VERSION line from ${SRC}: ${VERSION_LINE}" >&2
  exit 1
fi
UPSTREAM_DATE="${BASH_REMATCH[1]}T${BASH_REMATCH[2]}Z"
UPSTREAM_COMMIT="${BASH_REMATCH[3]}"

cp "${SRC}" "${DST}"

cat > "${VERSION_GO}" <<EOF
// SPDX-License-Identifier: GPL-2.0-or-later

// Code generated by scripts/sync-drivedb-go.sh from native/drivedb/drivedb.h; DO NOT EDIT.

package exec

// DrivedbUpstreamCommit is the upstream smartmontools commit SHA from which
// the embedded drivedb.h was taken.
const DrivedbUpstreamCommit = "${UPSTREAM_COMMIT}"

// DrivedbUpstreamDate is the commit date of DrivedbUpstreamCommit in RFC 3339 format.
const DrivedbUpstreamDate = "${UPSTREAM_DATE}"
EOF

echo "sync-drivedb-go.sh: synced drivedb.h (commit ${UPSTREAM_COMMIT}, ${UPSTREAM_DATE})"
