name: Build smartmontools-sdk (non-release)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  make-src-tgz:
    runs-on: ubuntu-latest
    name: Create smartmontools-sdk dist
    outputs:
      SOURCE_DATE_EPOCH: ${{ steps.set-env.outputs.SMARTMONTOOLS_GIT_REV_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ steps.set-env.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ steps.set-env.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
      artficact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 800
          fetch-tags: true
      - name: Setting environment variables
        id: set-env
        run: |
          src/getversion.sh -g >> $GITHUB_ENV
          cat $GITHUB_ENV | tee $GITHUB_OUTPUT

      - name: Creating src.tar.gz
        run: |
          ./autogen.sh --force &&
          mkdir build && cd build &&
          ../configure SOURCE_DATE_EPOCH=${SMARTMONTOOLS_GIT_REV_EPOCH} --with-devel=yes &&
          make dist && tar -tvzf "smartmontools-${SMARTMONTOOLS_PKG_VER}.tar.gz" &&
          mkdir artifacts &&
          echo ${SMARTMONTOOLS_GIT_REV_EPOCH} > artifacts/SOURCE_DATE_EPOCH &&
          touch -d @${SMARTMONTOOLS_GIT_REV_EPOCH} artifacts/SOURCE_DATE_EPOCH &&
          mv smartmontools-${SMARTMONTOOLS_PKG_VER}.tar.gz artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz

      - name: Upload artifacts
        id: artifact-upload-step
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: build/artifacts/
          retention-days: 1

  compile-linux-static-x86_64:
    name: Creating static x86_64 linux library
    needs: make-src-tgz
    runs-on: ubuntu-latest
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.make-src-tgz.outputs.artficact-id }}
          path: artifacts
      - name: build
        run: |
          tar -xvf artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz &&
          cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
          ../configure --with-build-info='(GHA Build)' --with-devel=yes \
            SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib ${GITHUB_WORKSPACE}/artifacts/include &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib/ &&
          cp -r ../include/smartmon ${GITHUB_WORKSPACE}/artifacts/include/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libsmartmon-linux-x86_64-static
          path: |
            artifacts/lib/libsmartmon.a
            artifacts/include/smartmon/
          retention-days: 1

  compile-linux-static-i386:
    name: Creating static i386 linux library
    needs: make-src-tgz
    runs-on: ubuntu-latest
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.make-src-tgz.outputs.artficact-id }}
          path: artifacts
      - name: install m32 dependencies
        run: sudo apt-get update && sudo apt-get install gcc-multilib g++-multilib
      - name: build
        run: |
          tar -xvf artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz &&
          cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
          setarch i686 ../configure --with-build-info='(GHA Build)' --with-devel=yes \
            CC="gcc -m32" CXX="g++ -m32" SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib ${GITHUB_WORKSPACE}/artifacts/include &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib/ &&
          cp -r ../include/smartmon ${GITHUB_WORKSPACE}/artifacts/include/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libsmartmon-linux-i386-static
          path: |
            artifacts/lib/libsmartmon.a
            artifacts/include/smartmon/
          retention-days: 1

  compile-darwin:
    name: Creating Darwin library
    needs: make-src-tgz
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dianlight/docker-build:master
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.make-src-tgz.outputs.artficact-id }}
          path: artifacts
      - name: build
        run: |
          export PATH=/usr/osxcross/bin/:$PATH &&
          export LD_LIBRARY_PATH=/usr/osxcross/lib &&
          tar -xvf artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz &&
          cd smartmontools-${SMARTMONTOOLS_PKG_VER} &&
          mkdir build && cd build &&
          ../configure --build=$(../config.guess) --host=x86_64-apple-darwin20.4 \
            --with-build-info='(GHA Build)' --with-devel=yes \
            'CC=o64-clang' 'CXX=o64-clang++' 'CFLAGS=-arch arm64 -arch x86_64' \
            'CXXFLAGS=-arch arm64 -arch x86_64 -stdlib=libc++' \
            SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib ${GITHUB_WORKSPACE}/artifacts/include &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib/ &&
          cp -r ../include/smartmon ${GITHUB_WORKSPACE}/artifacts/include/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libsmartmon-darwin
          path: |
            artifacts/lib/libsmartmon.a
            artifacts/include/smartmon/
          retention-days: 1

  compile-freebsd:
    name: Creating FreeBSD libraries
    needs: make-src-tgz
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dianlight/docker-build:master
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.make-src-tgz.outputs.artficact-id }}
          path: artifacts
      - name: FreeBSD 14 build
        run: |
          tar -xvf artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz &&
          cd smartmontools-${SMARTMONTOOLS_PKG_VER} &&
          mkdir build && cd build &&
          export TARGET="-target x86_64-unknown-freebsd14 --sysroot=/opt/cross-freebsd-14/" &&
          TARGET="$TARGET -isystem /opt/cross-freebsd-14/usr/include/c++/v1" &&
          ../configure --host=x86_64-pc-freebsd14 --with-build-info='(GHA Build)' --with-devel=yes \
            CC="clang $TARGET" CXX="clang++ $TARGET" SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib ${GITHUB_WORKSPACE}/artifacts/include &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib/ &&
          cp -r ../include/smartmon ${GITHUB_WORKSPACE}/artifacts/include/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libsmartmon-freebsd-14
          path: |
            artifacts/lib/libsmartmon.a
            artifacts/include/smartmon/
          retention-days: 1
      - name: cleanup
        run: rm -rf smartmontools-${SMARTMONTOOLS_PKG_VER}
      - name: FreeBSD 15 build
        run: |
          tar -xvf artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz &&
          cd smartmontools-${SMARTMONTOOLS_PKG_VER} &&
          mkdir build && cd build &&
          export TARGET="-target x86_64-unknown-freebsd15 --sysroot=/opt/cross-freebsd-15/" &&
          TARGET="$TARGET -isystem /opt/cross-freebsd-15/usr/include/c++/v1" &&
          ../configure --host=x86_64-pc-freebsd15 --with-build-info='(GHA Build)' --with-devel=yes \
            CC="clang $TARGET" CXX="clang++ $TARGET" SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib ${GITHUB_WORKSPACE}/artifacts/include &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib/ &&
          cp -r ../include/smartmon ${GITHUB_WORKSPACE}/artifacts/include/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libsmartmon-freebsd-15
          path: |
            artifacts/lib/libsmartmon.a
            artifacts/include/smartmon/
          retention-days: 1

  compile-windows:
    name: Creating Windows library
    needs: make-src-tgz
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dianlight/docker-build:master
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.make-src-tgz.outputs.artficact-id }}
          path: artifacts
      - name: Windows build
        run: |
          tar -xvf artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz &&
          cd smartmontools-${SMARTMONTOOLS_PKG_VER} &&
          mkdir build && cd build &&
          ../configure --build=$(../config.guess) --host=i686-w64-mingw32 \
            --with-build-info='(GHA Build)' --with-devel=yes \
            SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib32 ${GITHUB_WORKSPACE}/artifacts/include &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib32/ &&
          cp -r ../include/smartmon ${GITHUB_WORKSPACE}/artifacts/include/ &&
          cd .. && mkdir build64 && cd build64 &&
          ../configure --build=$(../config.guess) --host=x86_64-w64-mingw32 \
            --with-build-info='(GHA Build)' --with-devel=yes \
            SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib64 &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib64/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libsmartmon-windows
          path: |
            artifacts/lib32/libsmartmon.a
            artifacts/lib64/libsmartmon.a
            artifacts/include/smartmon/
          retention-days: 1

  compile-cygwin:
    name: Creating Cygwin library
    needs: make-src-tgz
    runs-on: ubuntu-latest
    container: fedora:latest
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
    steps:
      - name: Install build tools
        run: |
          dnf install -y make
      - name: Enable 'dnf copr'
        run: |
          dnf install -y dnf-plugins-core
      - name: Install cross-cygwin toolchain
        run: |
          dnf copr enable -y yselkowitz/cygwin
          dnf install -y cygwin64-gcc-c++
      - uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.make-src-tgz.outputs.artficact-id }}
          path: artifacts
      - name: Cygwin build
        run: |
          tar -xvf artifacts/smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz &&
          cd smartmontools-${SMARTMONTOOLS_PKG_VER} && mkdir build && cd build &&
          ../configure --build=$(../config.guess) --host=x86_64-pc-cygwin \
            --with-build-info='(GHA Build)' --with-devel=yes SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH} &&
          make -j -C lib &&
          mkdir -p ${GITHUB_WORKSPACE}/artifacts/lib ${GITHUB_WORKSPACE}/artifacts/include &&
          cp lib/.libs/libsmartmon.a ${GITHUB_WORKSPACE}/artifacts/lib/ &&
          cp -r ../include/smartmon ${GITHUB_WORKSPACE}/artifacts/include/
      - name: Upload library artifacts
        uses: actions/upload-artifact@v7
        with:
          name: libsmartmon-cygwin
          path: |
            artifacts/lib/libsmartmon.a
            artifacts/include/smartmon/
          retention-days: 1

  publish-artifacts:
    if: ${{ github.repository == 'dianlight/smartmontools-sdk' && github.ref == 'refs/heads/main' }}
    env:
      SOURCE_DATE_EPOCH: ${{ needs.make-src-tgz.outputs.SOURCE_DATE_EPOCH }}
      SMARTMONTOOLS_PKG_VER: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_PKG_VER }}
      SMARTMONTOOLS_GIT_VER_FNAME: ${{ needs.make-src-tgz.outputs.SMARTMONTOOLS_GIT_VER_FNAME }}
    name: publish-artifacts
    needs:
      - make-src-tgz
      - compile-linux-static-x86_64
      - compile-linux-static-i386
      - compile-darwin
      - compile-freebsd
      - compile-windows
      - compile-cygwin
    runs-on: ubuntu-latest
    environment:
      name: mainbranch
      url: https://github.com/dianlight/smartmontools-sdk-releases
    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: artifacts
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: dianlight
          repositories: smartmontools-sdk-releases
      - name: gh create delete (cleanup)
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh release delete "smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}" --repo dianlight/smartmontools-sdk-releases \
            --yes --cleanup-tag || true
      - name: gh create release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh release create "smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}" \
            artifacts/* \
            --repo dianlight/smartmontools-sdk-releases \
            --notes "Smartmontools SDK CI build: [smartmontools-sdk-${SMARTMONTOOLS_GIT_VER_FNAME}](https://github.com/dianlight/smartmontools-sdk/tree/${GITHUB_SHA})" \
            --prerelease
      - name: Clean old builds
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh -R dianlight/smartmontools-sdk-releases release list \
            -L 100 --json tagName -q '.[50:][]|.tagName' | \
            xargs -n1 --no-run-if-empty \
            gh -R dianlight/smartmontools-sdk-releases release delete --cleanup-tag --yes
