name: Build smartmontools-sdk on Cygwin

on: workflow_dispatch

jobs:
  build-cygwin-library:
    runs-on: windows-latest
    steps:
      - name: Install Cygwin and build tools
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86_64
          packages: |
            automake
            clang-analyzer
            gcc-g++
            git
            libtool
            make

      - run: git config --global --add safe.directory /cygdrive/d/a/smartmontools-sdk/smartmontools-sdk

      - uses: actions/checkout@v6
        with:
          set-safe-directory: false
          fetch-depth: 800
          fetch-tags: true

      - name: Set environment
        run: |
          export PATH=/usr/bin:$(cygpath ${SYSTEMROOT})/system32 && uname -a &&
          echo "PATH=$PATH" >> $GITHUB_ENV && src/getversion.sh -g >> $GITHUB_ENV
        shell: bash --noprofile --norc -e -o igncr '{0}'

      - run: ./autogen.sh
        shell: bash --noprofile --norc -e -o igncr '{0}'

      - name: Build library with x86_64 gcc
        run: |
          mkdir build-gcc && cd build-gcc &&
          ../configure --with-build-info='(GHA/Cygwin)' --with-devel=yes \
            SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
          make -C include && make -j -C lib &&
          mkdir -p lib include &&
          cp lib/.libs/libsmartmon.a lib/ &&
          cp -r ../include/smartmon include/ &&
          tar -czf "../smartmontools-sdk-cygwin-x86_64-gcc-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" lib include
        shell: bash --noprofile --norc -e -o igncr '{0}'

      - name: Upload gcc artifact
        uses: actions/upload-artifact@v7
        with:
          name: smartmontools-sdk-cygwin-gcc
          path: smartmontools-sdk-cygwin-x86_64-gcc-*.tar.gz
          retention-days: 30

      - name: Build library with x86_64 clang
        run: |
          mkdir build-clang && cd build-clang &&
          ../configure --with-build-info='(GHA/Cygwin)' --with-devel=yes CC=clang CXX=clang++ \
            SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
          ../src/clang-scan-build.sh \
            -f "smartmontools-sdk-cygwin-clang-report-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" \
            make -C include && make -j -C lib &&
          mkdir -p lib include &&
          cp lib/.libs/libsmartmon.a lib/ &&
          cp -r ../include/smartmon include/ &&
          tar -czf "../smartmontools-sdk-cygwin-x86_64-clang-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" lib include
        shell: bash --noprofile --norc -e -o igncr '{0}'

      - name: Upload clang artifact
        uses: actions/upload-artifact@v7
        with:
          name: smartmontools-sdk-cygwin-clang
          path: smartmontools-sdk-cygwin-x86_64-clang-*.tar.gz
          retention-days: 30

      - name: Upload clang static analyzer artifact
        uses: actions/upload-artifact@v7
        with:
          name: smartmontools-sdk-cygwin-clang-report
          path: build-clang/smartmontools-sdk-cygwin-clang-report-*.tar.gz
          retention-days: 30
