name: Build smartmontools-sdk on macOS

on: workflow_dispatch

jobs:
  build-macos-library:
    runs-on: macos-latest
    steps:
      - name: Install build tools
        run: |
          brew install automake
          brew install libtool

      - uses: actions/checkout@v6
        with:
          set-safe-directory: false
          fetch-depth: 800
          fetch-tags: true

      - name: Set environment
        run: src/getversion.sh -g >> $GITHUB_ENV

      - run: ./autogen.sh

      - name: Build library (multiarch)
        run: |
          mkdir build && cd build &&
          ../configure --with-build-info='(GHA/macOS)' --with-devel=yes \
            CFLAGS='-arch arm64 -arch x86_64' CXXFLAGS='-arch arm64 -arch x86_64' \
            SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
          make -j -C lib &&
          mkdir -p lib include &&
          cp lib/.libs/libsmartmon.a lib/ &&
          cp -r ../include/smartmon include/ &&
          tar -czf "../smartmontools-sdk-macos-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" lib include

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: smartmontools-sdk-macos
          path: smartmontools-sdk-macos-*.tar.gz
          retention-days: 30
