name: Build smartmontools-sdk on MSYS2

on: workflow_dispatch

jobs:
  build-on-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw32, env: i686 }
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
          - { sys: clang64, env: clang-x86_64 }

    steps:
      - name: Install MSYS2 and ${{matrix.env}} build tools
        uses: msys2/setup-msys2@v2
        with:
          release: false
          msystem: ${{matrix.sys}}
          install: >-
            mingw-w64-${{matrix.env}}-gcc
            autoconf
            automake
            libtool
            make
            git

      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v6
        with:
          fetch-depth: 800
          fetch-tags: true

      - name: Build library (${{matrix.env}})
        run: |
          version_sh=$(src/getversion.sh -s) && eval "${version_sh}" &&
          ./autogen.sh && mkdir build && cd build &&
          ../configure --with-build-info='(GHA/MSYS2)' --with-devel=yes \
            SOURCE_DATE_EPOCH=$((SMARTMONTOOLS_GIT_REV_EPOCH + 1)) &&
          make -C include && make -j -C lib &&
          mkdir -p lib include &&
          cp lib/.libs/libsmartmon.* lib/ &&
          cp -r ../include/smartmon include/ &&
          tar -czf "../smartmontools-sdk-mingw64-${{matrix.env}}-${SMARTMONTOOLS_GIT_VER_FNAME}.tar.gz" lib include
        shell: msys2 '{0}'

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: smartmontools-sdk-mingw64-${{matrix.env}}
          path: smartmontools-sdk-mingw64-${{matrix.env}}-*.tar.gz
          retention-days: 30
